# k8s/ingress.yaml
# Define el Ingress, que gestiona el acceso externo a los servicios del clúster.
# Al aplicar este manifiesto, GKE creará automáticamente un Balanceador de Carga de Google Cloud
# para dirigir el tráfico HTTP/S a tu API Gateway.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    # Esta anotación es importante para GKE.
    kubernetes.io/ingress.class: "gce"
spec:
  # 'defaultBackend' dirige todo el tráfico que no coincide con ninguna regla
  # al servicio especificado. Perfecto para un API Gateway.
  defaultBackend:
    service:
      name: api-gateway
      port:
        number: 80
