# k8s/kustomization.yaml
# Este archivo le permite a la herramienta 'kustomize' (integrada en kubectl)
# saber qué recursos forman parte de tu aplicación.
# Esto simplifica el despliegue, ya que puedes aplicar todos los archivos
# con un solo comando en lugar de hacerlo uno por uno.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lista de todos los archivos de manifiesto que componen tu aplicación.
resources:
- secrets.yaml
- api-gateway.yaml
- auth-service.yaml
- user-service.yaml
- role-service.yaml
- permission-service.yaml
- ingress.yaml
