# k8s/secrets.yaml
# Este archivo define los secretos que usarán tus aplicaciones.
# Es crucial para manejar información sensible como contraseñas de bases de datos.

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # IMPORTANTE: Reemplaza 'UNA_CONTRASENA_SEGURA' por la contraseña real que creaste en Cloud SQL.
  # stringData lo codificará automáticamente a base64 por ti al aplicarlo.
  password: "D0f94248c1."
  # IMPORTANTE: Reemplaza 'himfg_user' si usaste un nombre de usuario diferente.
  username: "himfg_user"
